/*
 *  !!! TEST FILE !!!
 */

#include "Fusion/FusionTrace.h"
#include "Fusion/FusionTypes.h"
#include <Fusion/Fusion.h>

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include <time.h>

// TODO:
// - Stack protector
// - Stack alignment (ABI)
// - SUB/ADD explícito para RSP
// - PUSH/POP de RSP
//
// libc utiliza SSE e exige alinhamento correto da stack.

static void Hello()
{
    puts("Executado via JIT!");
}

typedef void (*FusionEntryPoint)(void);

int main(void)
{
    struct timespec start, end;

    FusInstance instance = NULL;
    FusCodeMount mount = NULL;
    FusLinkerContext linker = NULL;
    FusModuleBackend x86 = NULL;
    FusBackendReturn compiler = NULL;
    FusTraceTree_t trace = NULL;

    FusBufferContext_t* buffer = NULL;

    FILE* file = NULL;

    clock_gettime(CLOCK_MONOTONIC, &start);

    if (FUS_CreateInstance(&instance, NULL) != FUSION_OK) {
        printf("Failed to create Fusion instance\n");
        return 1;
    }

    if (FUS_InstanceGetTrace(instance,&trace) != FUSION_OK) {
        printf("Erro to get trace instance\n");
        FUS_DestroyInstance(&instance);
        return 1;
    }

    if (FUS_CreateCodeMount(&instance, &mount) != FUSION_OK) {
        printf("Failed to create code mount\n");
        goto cleanup;
    }

    FUS_InsertCodeBlock(mount,
        FUS_HIDRM(HIDR_INSTR_MOV, HIDR_OP_SIZE_64,
            FUS_HIDR_Reg(1),
            FUS_HIDR_Sym("Hello")
        )
    );
    FUS_InsertCodeBlock(mount,
        FUS_HIDRM(HIDR_INSTR_CALL, HIDR_OP_SIZE_64,
            FUS_HIDR_Reg(1),
            FUS_HIDR_None()
        )
    );
    FUS_InsertCodeBlock(mount,
        FUS_HIDRM(HIDR_INSTR_RET, HIDR_OP_SIZE_NONE,
            FUS_HIDR_None(),
            FUS_HIDR_None()
        )
    );

    if (FUS_CreateLinkerContext(&instance,&linker) != FUSION_OK) {
        printf("Failed to create linker context\n");
        goto cleanup;
    }
    printf("Hello address: %p\n", &Hello);

    FUS_AddSymbolLinker(
        linker,
        "Hello",
        (uintptr_t)&Hello
    );

    FUS_LoaderBackend(
        &instance,
        &x86,
        "X86_Backend",
        FUS_BACKEND_TYPE_STATIC
    );
    FusCommandBackend backendCmd = {
        .sType = FUS_COMMAND_SEND_BACKEND,
        .pNext = NULL,
        .backend = x86
    };

    FusCommandHidr hidrCmd = {
        .sType = FUS_COMMAND_SEND_HIDR,
        .pNext = (FusCommandRuleBase_t*)&backendCmd,
        .code = mount
    };

    if (FUS_MountHidrsBytes(
        &instance,
        (FusCommandRuleBase_t*)&hidrCmd,
        &compiler
    ) != FUSION_OK) {
        printf("Erro em copilar!\n");
        goto cleanup;
    }

    if (!compiler) {
        printf("Compilation failed\n");
        goto cleanup;
    }

    FusCommandBackend linkerCmd = {
        .sType = FUS_COMMAND_SEND_BACKEND,
        .pNext = NULL,
        .backend = x86
    };
    if (FUS_LinkerResolver(
            (FusCommandRuleBase_t*)&linkerCmd,
            linker,
            compiler) != FUSION_OK) {
        printf("Linking failed\n");
        goto cleanup;
    }
    buffer = FUS_GetStreamBufferCompiler(compiler);

    if (!buffer) {
        printf("No output buffer attached\n");
        goto cleanup;
    }

    printf("Generated bytes:\n");

    for (size_t i = 0; i < buffer->offset; ++i) {
        printf(" %02X", buffer->buffer[i]);
    }

    printf("\n");
    file = fopen("out.bin", "wb");

    if (FUS_ExecutableBuffer(buffer) == FUSION_OK) {
        FusionEntryPoint entry = (FusionEntryPoint)buffer->buffer;
        entry();
    } else {
        printf("Execução Falhou!\n");
    }

    FUS_DumpTrace(trace);
    clock_gettime(CLOCK_MONOTONIC, &end);

cleanup:

    if (file) fclose(file);
    if (buffer) FUS_DestroyBufferCode(buffer);
    if (mount) FUS_DestroyCodeMount(&instance, mount);
    if (compiler) FUS_DestroyCompiler(instance, compiler);
    if (x86) FUS_DestroyBackend(x86);
    if (linker) FUS_DestroyLinkerContext(instance, linker);
    if (instance) FUS_DestroyInstance(&instance);

    long long ns =
        (end.tv_sec - start.tv_sec) * 1000000000LL +
        (end.tv_nsec - start.tv_nsec);

    printf(
        "\nExecute Time: %lld ns (%.3f us)\n",
        ns,
        (double)ns / 1000.0
    );
    return 0;
}