/*
 *  !!! TEST FILE !!!
 */

#include "Fusion/IRTypes/HidrHelper.h"
#include "Fusion/IRTypes/HidrType.h"
#include <Fusion/Fusion.h>

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <time.h>

// TODO:
// - Stack protector
// - Stack alignment (ABI)
// - SUB/ADD explícito para RSP
// - PUSH/POP de RSP
//
// libc utiliza SSE e exige alinhamento correto da stack.

static void Hello()
{
    puts("Executado via JIT!");
}

typedef void (*FusionEntryPoint)(void);

int main(void)
{
    struct timespec start, end;

    FusInstance instance = NULL;
    FusCodeMount_t mount = NULL;
    FusLinkerContext_t* linker = NULL;
    FusModuleBackend_t x86 = NULL;
    FusBackendReturn_t* compiler = NULL;
    FusBufferContext_t* buffer = NULL;

    FILE* file = NULL;

    clock_gettime(CLOCK_MONOTONIC, &start);

    if (FUS_CreateInstance(&instance, NULL) != FUSION_OK) {
        printf("Failed to create Fusion instance\n");
        return 1;
    }

    if (FUS_CreateCodeMount(&instance, &mount) != FUSION_OK) {
        printf("Failed to create code mount\n");
        goto cleanup;
    }

    FUS_NewMov(
        mount,
        FUS_NewRegistre(1),
        FUS_NewSymbol("Hello")
    );
    FUS_NewCallReg(mount, 1);
    FUS_NewRet(mount);
    linker = FUS_CreateLinkerContext(&instance);

    if (!linker) {
        printf("Failed to create linker context\n");
        goto cleanup;
    }
    printf("Hello address: %p\n", &Hello);

    FUS_AddSymbolLinker(
        linker,
        "Hello",
        (uintptr_t)&Hello
    );

    FUS_LoaderBackend(
        &instance,
        &x86,
        "X86_Backend",
        FUS_BACKEND_TYPE_STATIC
    );
    FusCommandBackend backendCmd = {
        .sType = FUS_COMMAND_SEND_BACKEND,
        .pNext = NULL,
        .backend = x86
    };

    FusCommandHidr hidrCmd = {
        .sType = FUS_COMMAND_SEND_HIDR,
        .pNext = (FusCommandRuleBase_t*)&backendCmd,
        .hidr_arry = FUS_GetArryCode(mount),
        .hidr_count = FUS_GetCountCode(mount)
    };

    compiler = FUS_MountHidrsBytes(
        &instance,
        (FusCommandRuleBase_t*)&hidrCmd
    );

    if (!compiler) {
        printf("Compilation failed\n");
        goto cleanup;
    }

    FusCommandBackend linkerCmd = {
        .sType = FUS_COMMAND_SEND_BACKEND,
        .pNext = NULL,
        .backend = x86
    };
    if (FUS_LinkerResolver(
            (FusCommandRuleBase_t*)&linkerCmd,
            linker,
            compiler) != FUSION_OK) {
        printf("Linking failed\n");
        goto cleanup;
    }
    buffer = FUS_GetStreamBufferCompiler(compiler);

    if (!buffer) {
        printf("No output buffer attached\n");
        goto cleanup;
    }

    printf("Generated bytes:\n");

    for (size_t i = 0; i < buffer->offset; ++i) {
        printf(" %02X", buffer->buffer[i]);
    }

    printf("\n");
    file = fopen("out.bin", "wb");

    if (file) {
        fwrite(
            buffer->buffer,
            buffer->offset,
            1,
            file
        );
        fclose(file);
        file = NULL;
    }
    FUS_ExecutableBuffer(buffer);

    FusionEntryPoint entry = (FusionEntryPoint)buffer->buffer;
    entry();

    clock_gettime(CLOCK_MONOTONIC, &end);

cleanup:

    if (file) fclose(file);
    if (buffer) FUS_DestroyBufferCode(buffer);
    if (mount) FUS_DestroyCodeMount(&instance, mount);
    if (compiler) FUS_DestroyCompiler(instance, compiler);
    if (x86) FUS_DestroyBackend(x86);
    if (linker) FUS_DestroyLinkerContext(instance, linker);
    if (instance) FUS_DestroyInstance(&instance);

    long long ns =
        (end.tv_sec - start.tv_sec) * 1000000000LL +
        (end.tv_nsec - start.tv_nsec);

    printf(
        "\nExecute Time: %lld ns (%.3f us)\n",
        ns,
        (double)ns / 1000.0
    );
    return 0;
}