/**
 * ███████╗██╗   ██╗███████╗██╗ ██████╗ ███╗   ██╗
 * ██╔════╝██║   ██║██╔════╝██║██╔═══██╗████╗  ██║
 * █████╗  ██║   ██║███████╗██║██║   ██║██╔██╗ ██║
 * ██╔══╝  ██║   ██║╚════██║██║██║   ██║██║╚██╗██║
 * ██║     ╚██████╔╝███████║██║╚██████╔╝██║ ╚████║
 * ╚═╝      ╚═════╝ ╚══════╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝
 *
 * @file    bufferio_utils.c
 * @brief   Writing a buffer to an IO sink.
 * @author     Ewerton23929dev
 *
 * @details
 * Forwards the already generated bytes to the destination chosen by the user and
 * validates the involved handles before the call.
 * @copyright  Copyright (c) 2026 Ewerton23929dev. All rights reserved.
 */

#include <Fusion/Fusion.h>
#include <Fusion/FusionTypes.h>
#include <Fusion/IO/FusionGenericIO.h>
#include <Internal/IO/Fus_GenericIO.h>

// HELPER
#include <Internal/Helpers/Fus_Helper_Codebase.h>

FusStatusFlag_t fusBufferIOSink(FusBufferController* buffer, FusIOSink sink)
{
    if (unlikely(!buffer || !sink)) return FUSION_ERRO;
    sink->interface.write(sink->ctx,buffer->data,buffer->offset);
    return FUSION_OK;
}